### PR TITLE
Fix code climate rating

### PR DESCRIPTION
**Pull request by theninj4**
CodeClimate is including the browserified test bundle in its ratings, which is wildly degrading the score. This PR adds a `.codeclimate.yml` file to tell codeclimate to ignore the `/dist` folder.

### CODE REVIEW

**Comment by pmcnr-hx** [comment]
:+1: :shipit: after master is merged and all is green.

**Comment by theninj4** [comment]
Result: https://codeclimate.com/github/holidayextras/jsonapi-client/compare/codeclimate#ratings

**Comment by theninj4** [comment]
@pmcnr-hx  the build won't go green due to iOS 9.2 :'(

**Comment by theninj4** [comment]
```
Chrome 47.0.2526 (Windows 10 0.0.0): Executed 22 of 23 (skipped 1) SUCCESS (5.651 secs / 4.736 secs)
Firefox 43.0.0 (Windows 10 0.0.0): Executed 22 of 23 (skipped 1) SUCCESS (5.82 secs / 5.273 secs)
IE 11.0.0 (Windows 10 0.0.0): Executed 22 of 23 (skipped 1) SUCCESS (5.498 secs / 4.741 secs)
IE 9.0.0 (Windows 7 0.0.0): Executed 22 of 23 (skipped 1) SUCCESS (3.974 secs / 3.338 secs)
Chrome Mobile 39.0.0 (Android 5.1.0): Executed 22 of 23 (skipped 1) SUCCESS (4.628 secs / 3.848 secs)
Mobile Safari 9.0.0 (iOS 9.2.0): Executed 11 of 23 (10 FAILED) (skipped 1) (2.228 secs / NaN secs)
Mobile Safari 7.0.0 (iOS 7.1.0): Executed 22 of 23 (skipped 1) SUCCESS (4.4 secs / 3.77 secs)
```

**Comment by connormeredith** [comment]
:+1:

**Pull request merged**
